config/routes.rb
BlankSite::Application.routes.draw do
  mount Mercury::Engine => '/'

  root to: 'home#index'
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  match '/:page_url' => 'home#page'
  put   '/:page_url/mercury_page_update' => 'home#mercury_page_update', :as => :mercury_page_update
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates_presence_of :page_url
  validates_uniqueness_of :page_url
  attr_protected
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_protected
  before_save :clean_domain

  validates_presence_of :domain
  
  private

  def clean_domain
    self.domain = self.domain.gsub('www.', '').strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_site

  def current_site
    @current_site ||= Site.find_by_domain(request.host.gsub('www.', '')) || Site.new(domain: 'example.com', header: 'Site Header', footer: 'Site Footer')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'bootstrap'

  def index
    @page = Page.find_by_page_url('index') || demo_page
    setup_page(@page)
    render action: :page
  end

  def page
    redirect_to '/' and return if params[:page_url] == 'index'
    @page = Page.find_by_page_url params[:page_url]
    setup_page(@page)
  end

  def mercury_page_update
    @page = Page.find_by_page_url params[:page_url]
    @page.content = params[:content][:content][:value] rescue nil
    @page.save!
    render text: ""
  end

  protected
  def setup_page(page)
    @title = page.title
    @meta_description = @page.meta_description
    @content = page.content
    @editable = true if page.persisted?
  end

  def demo_page
    Page.new(title: "Demo Index Page", content: view_context.demo_content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash
    close_button = content_tag :button, '&times;'.html_safe, class: 'close', data: {dismiss: 'alert'}, aria: {hidden: 'true'}
    output = []
    flash.each do |k,v|
      case k
      when :notice
        output << content_tag(:div, close_button + v, class: 'alert alert-success alert-dismissable')
      when :info
        output << content_tag(:div, close_button + v, class: 'alert alert-info alert-dismissable')
      when :error
        output << content_tag(:div, close_button + v, class: 'alert alert-danger alert-dismissable')
      else
        output << content_tag(:div, close_button + v, class: 'alert alert-warning alert-dismissable')
      end
    end
    output.join.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def demo_content
    content = <<-content
Welcome to Blank Site

This page is auto generated until you make your own Page with page.page_url == 'index'

To access the backend, login at /admin with admin@example.com and password 'password'

Once you create a page and are logged in, you will see an edit link on the top right to edit the page inline.
content
    content_tag(:pre, content)
  end
end

app/views/home/page.html.haml
#content{data: {mercury: 'full'}}
  = raw @content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= @title || current_site.domain
    %meta{name: 'description', content: @meta_description}
    %meta{name: 'keywords', content: @meta_keywords}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{:class => @body_class}
    - if current_admin_user && @editable && @page
      #edit_link
        = link_to 'Edit Page', "/editor/" + @page.page_url, data: {save_url: mercury_page_update_path(@page.page_url)}

    %header= raw current_site.header
    .main= yield
    %footer= raw current_site.footer

app/views/layouts/bootstrap.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= @title || current_site.domain
    %meta{name: 'description', content: @meta_description}
    %meta{name: 'keywords', content: @meta_keywords}
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    - if current_admin_user && @editable && @page
      #edit_link
        = link_to 'Edit Page', "/editor/" + @page.page_url, data: {save_url: mercury_page_update_path(@page.page_url)}
    #wrap
      %header#header
        .container= raw current_site.header
      #main.container
        #flash= bootstrap_flash
        = yield
    
    %footer#footer
      .container= raw current_site.footer

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js' %>
    <%= javascript_include_tag 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  null, // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>